data:
  _target_: tsa.dataset.TimeSeriesDataset
  batch_size: 4
  categorical_cols: [ ]
  index_col: "index"
  target_col: [ ]
  data_path: "../../data/raw/toy_dataset.csv"
  prediction_window: 1
  seq_length: 3
  task:
    _target_: tsa.dataset.Tasks
    value: reconstruction

training:
  denoising: False
  directions: 1
  gradient_accumulation_steps: 1
  hidden_size_encoder: 2
  hidden_size_decoder: 2
  input_att: True
  lr: 1e-5
  lrs_step_size: 5000
  max_grad_norm: 0.1
  num_epochs: 100
  output_size: 2
  reg1: True
  reg2: False
  reg_factor1: 1e-4
  reg_factor2: 1e-4
  seq_len: ${data.seq_length}
  temporal_att: True

general:
  do_eval: True
  do_train: True
  logging_steps: 100
  output_dir: "output"
  save_steps: 1
  eval_during_training: True
  ckpt: "checkpoint-60.ckpt"
