data:
  _target_: tsa.dataset.TimeSeriesDataset
  batch_size: 4
  categorical_cols: [ ]
  index_col: "index"
  target_col: [ "B2" ]
  data_path: "../../data/raw/toy_dataset.csv"
  prediction_window: 1
  seq_length: 3
  task:
    _target_: tsa.dataset.Tasks
    value: inference

model:
  name: predict